[package]
name = "HotVectors"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = {version = "*", features = ["v4", "serde"]}
bitcode = "=0.6.3"
serde = {version = "1.0.215", features = ["derive"]}
petgraph = "0.6.5"
heapify = "0.2.0"
chrono = "*"