[package]
name = "HotVectors"
version = "0.1.0"
edition = "2021"

[features]
gpu_processing = []

# rest = ["axum"]

[dependencies]
uuid = {version = "*", features = ["v4", "serde"]}
rkyv = {version = "*", features = ["bytecheck", "alloc"]}
rancor = "0.1.0"
serde = {version = "1.0.215", features = ["derive"]}
petgraph = "0.6.5"
heapify = "0.2.0"
chrono = "*"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }

tracing = "0.1"
tracing-subscriber = "0.3.19"

# async_sqlite = "*"

# Conditional dependency for REST API
axum = { version = "0.8.1", features = ["macros"]}#, optional = true}